import type {
  ReportTemplate,
  GeneratedReport,
  ComplianceFramework,
  DashboardStats,
  Scan,
  Vulnerability,
  Threat,
} from "./types"

// --- Dashboard Stats ---
export const dashboardStats: DashboardStats = {
  totalScans: 48,
  activeScans: 3,
  criticalVulns: 12,
  complianceScore: 84,
  threatsDetected: 7,
  assetsMonitored: 1243,
  totalScansChange: 6,
  activeScanChange: 1,
  criticalVulnsChange: -3,
  complianceChange: 2,
  threatsChange: -1,
  assetsChange: 54,
}

// --- Scans ---
export const scans: Scan[] = [
  {
    id: "scan-001",
    name: "Production AWS Audit",
    target: "aws://prod-account",
    scanScope: "full",
    status: "completed",
    startTime: "2026-02-20T08:00:00Z",
    endTime: "2026-02-20T09:15:00Z",
    findingsCount: 34,
    progress: 100,
    criticalCount: 4,
    highCount: 8,
    cloudProvider: "AWS",
  },
  {
    id: "scan-002",
    name: "Azure DevOps Scan",
    target: "azure://devops-sub",
    scanScope: "full",
    status: "completed",
    startTime: "2026-02-19T14:00:00Z",
    endTime: "2026-02-19T15:30:00Z",
    findingsCount: 21,
    progress: 100,
    criticalCount: 2,
    highCount: 5,
    cloudProvider: "Azure",
  },
  {
    id: "scan-003",
    name: "GCP Kubernetes Cluster",
    target: "gcp://k8s-prod",
    scanScope: "full",
    status: "running",
    startTime: "2026-02-21T10:00:00Z",
    endTime: null,
    findingsCount: 12,
    progress: 67,
    criticalCount: 1,
    highCount: 3,
    cloudProvider: "GCP",
  },
  {
    id: "scan-004",
    name: "AWS S3 Bucket Review",
    target: "aws://s3-buckets",
    scanScope: "full",
    status: "completed",
    startTime: "2026-02-18T09:00:00Z",
    endTime: "2026-02-18T09:45:00Z",
    findingsCount: 8,
    progress: 100,
    criticalCount: 1,
    highCount: 2,
    cloudProvider: "AWS",
  },
  {
    id: "scan-005",
    name: "Azure Network Scan",
    target: "azure://network-sub",
    scanScope: "ports",
    status: "pending",
    startTime: "2026-02-22T08:00:00Z",
    endTime: null,
    findingsCount: 0,
    progress: 0,
    criticalCount: 0,
    highCount: 0,
    cloudProvider: "Azure",
  },
  {
    id: "scan-006",
    name: "GCP IAM Audit",
    target: "gcp://iam-project",
    scanScope: "full",
    status: "running",
    startTime: "2026-02-21T12:00:00Z",
    endTime: null,
    findingsCount: 5,
    progress: 42,
    criticalCount: 2,
    highCount: 1,
    cloudProvider: "GCP",
  },
]

// --- Vulnerabilities ---
export const vulnerabilities: Vulnerability[] = [
  {
    id: "vuln-001",
    title: "Publicly Accessible S3 Bucket",
    severity: "critical",
    category: "Storage",
    cvssScore: 9.8,
    affectedResource: "arn:aws:s3:::prod-data-exports",
    cloudProvider: "AWS",
    status: "open",
    description: "S3 bucket has public read access enabled, exposing sensitive data.",
    remediation: "Disable public access and enable bucket-level encryption.",
    scanId: "scan-001",
    discoveredAt: "2026-02-20T08:22:00Z",
  },
  {
    id: "vuln-002",
    title: "Unencrypted RDS Instance",
    severity: "high",
    category: "Database",
    cvssScore: 7.5,
    affectedResource: "arn:aws:rds:us-east-1:prod-db",
    cloudProvider: "AWS",
    status: "in_progress",
    description: "RDS instance does not have encryption at rest enabled.",
    remediation: "Enable encryption at rest using AWS KMS.",
    scanId: "scan-001",
    discoveredAt: "2026-02-20T08:30:00Z",
  },
  {
    id: "vuln-003",
    title: "Overly Permissive NSG Rule",
    severity: "critical",
    category: "Network",
    cvssScore: 9.1,
    affectedResource: "azure://nsg-devops-001",
    cloudProvider: "Azure",
    status: "open",
    description: "Network security group allows inbound traffic from 0.0.0.0/0 on all ports.",
    remediation: "Restrict inbound rules to known IP ranges and required ports only.",
    scanId: "scan-002",
    discoveredAt: "2026-02-19T14:18:00Z",
  },
  {
    id: "vuln-004",
    title: "Exposed Kubernetes Dashboard",
    severity: "high",
    category: "Container",
    cvssScore: 8.2,
    affectedResource: "gcp://k8s-prod/dashboard",
    cloudProvider: "GCP",
    status: "open",
    description: "Kubernetes dashboard is publicly accessible without authentication.",
    remediation: "Restrict dashboard access with RBAC and network policies.",
    scanId: "scan-003",
    discoveredAt: "2026-02-21T10:15:00Z",
  },
  {
    id: "vuln-005",
    title: "Outdated TLS Configuration",
    severity: "medium",
    category: "Encryption",
    cvssScore: 5.3,
    affectedResource: "azure://app-gateway-01",
    cloudProvider: "Azure",
    status: "open",
    description: "Application gateway supports TLS 1.0 and 1.1 which are deprecated.",
    remediation: "Configure minimum TLS version to 1.2.",
    scanId: "scan-002",
    discoveredAt: "2026-02-19T14:45:00Z",
  },
  {
    id: "vuln-006",
    title: "IAM User with Stale Credentials",
    severity: "medium",
    category: "Identity",
    cvssScore: 6.1,
    affectedResource: "arn:aws:iam::user/deploy-bot",
    cloudProvider: "AWS",
    status: "remediated",
    description: "IAM user has access keys that have not been rotated in over 90 days.",
    remediation: "Rotate access keys and enforce automated rotation policy.",
    scanId: "scan-004",
    discoveredAt: "2026-02-18T09:12:00Z",
  },
  {
    id: "vuln-007",
    title: "Missing Firewall Rules on GCE Instance",
    severity: "high",
    category: "Compute",
    cvssScore: 7.8,
    affectedResource: "gcp://compute/web-server-01",
    cloudProvider: "GCP",
    status: "open",
    description: "GCE instance lacks firewall rules, allowing all ingress traffic.",
    remediation: "Apply VPC firewall rules to restrict traffic to required ports.",
    scanId: "scan-003",
    discoveredAt: "2026-02-21T10:30:00Z",
  },
  {
    id: "vuln-008",
    title: "Unused Security Group with Wide Ingress",
    severity: "low",
    category: "Network",
    cvssScore: 3.2,
    affectedResource: "arn:aws:ec2:sg-legacy-001",
    cloudProvider: "AWS",
    status: "accepted",
    description: "Unused security group allows inbound on port 22 from 0.0.0.0/0.",
    remediation: "Delete the unused security group or restrict its ingress rules.",
    scanId: "scan-001",
    discoveredAt: "2026-02-20T08:50:00Z",
  },
]

// --- Threats ---
export const threats: Threat[] = [
  {
    id: "threat-001",
    type: "Brute Force Attack",
    severity: "high",
    source: "203.0.113.42",
    description: "Multiple failed SSH login attempts detected from suspicious IP.",
    timestamp: "2026-02-21T06:12:00Z",
    status: "active",
    relatedFindings: 3,
    recommendedAction: "Block the source IP and enable MFA for all SSH access.",
    scanId: "scan-001",
  },
  {
    id: "threat-002",
    type: "Data Exfiltration Attempt",
    severity: "critical",
    source: "Internal - prod-lambda-07",
    description: "Unusual outbound data transfer detected from Lambda function to unknown endpoint.",
    timestamp: "2026-02-20T22:45:00Z",
    status: "investigating",
    relatedFindings: 2,
    recommendedAction: "Isolate the Lambda function and review its IAM permissions.",
    scanId: "scan-001",
  },
  {
    id: "threat-003",
    type: "Privilege Escalation",
    severity: "critical",
    source: "azure://devops-sub/user-038",
    description: "User account escalated to Global Admin without approval workflow.",
    timestamp: "2026-02-20T18:30:00Z",
    status: "active",
    relatedFindings: 1,
    recommendedAction: "Revoke elevated privileges and audit recent admin actions.",
    scanId: "scan-002",
  },
  {
    id: "threat-004",
    type: "Cryptomining Activity",
    severity: "high",
    source: "gcp://compute/worker-node-12",
    description: "High CPU usage and connections to known mining pool IPs detected.",
    timestamp: "2026-02-21T03:00:00Z",
    status: "active",
    relatedFindings: 1,
    recommendedAction: "Terminate the compromised instance and investigate access logs.",
    scanId: "scan-003",
  },
  {
    id: "threat-005",
    type: "Unauthorized API Calls",
    severity: "medium",
    source: "aws://cloudtrail/unknown-agent",
    description: "API calls from unrecognized user agent accessing IAM endpoints.",
    timestamp: "2026-02-19T15:22:00Z",
    status: "resolved",
    relatedFindings: 4,
    recommendedAction: "Review CloudTrail logs and rotate affected credentials.",
    scanId: "scan-004",
  },
  {
    id: "threat-006",
    type: "Suspicious DNS Query",
    severity: "medium",
    source: "gcp://dns/query-log",
    description: "DNS queries to known command-and-control domains detected.",
    timestamp: "2026-02-21T09:10:00Z",
    status: "investigating",
    relatedFindings: 2,
    recommendedAction: "Block the domains and scan affected workloads for malware.",
    scanId: "scan-003",
  },
]

// --- Vulnerability Trend (30 days) ---
export const vulnerabilityTrend = [
  { date: "2026-01-24", critical: 8, high: 14, medium: 22, low: 31 },
  { date: "2026-01-26", critical: 9, high: 15, medium: 21, low: 29 },
  { date: "2026-01-28", critical: 7, high: 13, medium: 23, low: 30 },
  { date: "2026-01-30", critical: 10, high: 16, medium: 20, low: 28 },
  { date: "2026-02-01", critical: 11, high: 18, medium: 24, low: 32 },
  { date: "2026-02-03", critical: 10, high: 17, medium: 22, low: 30 },
  { date: "2026-02-05", critical: 12, high: 19, medium: 25, low: 33 },
  { date: "2026-02-07", critical: 11, high: 16, medium: 23, low: 31 },
  { date: "2026-02-09", critical: 13, high: 18, medium: 21, low: 29 },
  { date: "2026-02-11", critical: 14, high: 20, medium: 24, low: 34 },
  { date: "2026-02-13", critical: 12, high: 17, medium: 22, low: 30 },
  { date: "2026-02-15", critical: 11, high: 15, medium: 20, low: 28 },
  { date: "2026-02-17", critical: 13, high: 18, medium: 23, low: 31 },
  { date: "2026-02-19", critical: 12, high: 16, medium: 21, low: 29 },
  { date: "2026-02-21", critical: 12, high: 17, medium: 22, low: 30 },
]

// --- Compliance Frameworks ---
export const complianceFrameworks: ComplianceFramework[] = [
  {
    name: "CIS Benchmarks",
    shortName: "CIS",
    score: 87,
    totalControls: 142,
    passedControls: 124,
    failedControls: 14,
    naControls: 4,
    controls: [],
    scanId: "scan-001",
  },
  {
    name: "ISO 27001",
    shortName: "ISO",
    score: 74,
    totalControls: 114,
    passedControls: 84,
    failedControls: 26,
    naControls: 4,
    controls: [],
    scanId: "scan-001",
  },
  {
    name: "NIST CSF",
    shortName: "NIST",
    score: 91,
    totalControls: 108,
    passedControls: 98,
    failedControls: 8,
    naControls: 2,
    controls: [],
    scanId: "scan-001",
  },
]

// --- Report Templates ---
export const reportTemplates: ReportTemplate[] = [
  {
    id: "rpt-exec",
    name: "Executive Summary",
    description: "High-level security posture overview with risk scores, key findings, and strategic recommendations for leadership.",
    type: "executive",
    lastGenerated: "2026-02-19T10:00:00Z",
  },
  {
    id: "rpt-tech",
    name: "Technical Breakdown",
    description: "Detailed technical analysis of all discovered vulnerabilities with CVSS scores, attack vectors, and remediation steps.",
    type: "technical",
    lastGenerated: "2026-02-18T14:30:00Z",
  },
  {
    id: "rpt-comp",
    name: "Compliance Report",
    description: "Comprehensive compliance assessment against CIS, ISO 27001, and NIST frameworks with control-by-control analysis.",
    type: "compliance",
    lastGenerated: "2026-02-15T09:00:00Z",
  },
  {
    id: "rpt-full",
    name: "Full Audit Report",
    description: "Complete penetration testing report including methodology, scope, all findings, evidence, and remediation roadmap.",
    type: "full",
    lastGenerated: null,
  },
]

// --- Generated Reports ---
export const generatedReports: GeneratedReport[] = [
  { id: "gen-001", name: "Executive Summary - Feb 2026", type: "executive", generatedAt: "2026-02-19T10:00:00Z", size: "2.4 MB", status: "ready" },
  { id: "gen-002", name: "Technical Breakdown - Feb 2026", type: "technical", generatedAt: "2026-02-18T14:30:00Z", size: "8.1 MB", status: "ready" },
  { id: "gen-003", name: "CIS Compliance - Q1 2026", type: "compliance", generatedAt: "2026-02-15T09:00:00Z", size: "5.6 MB", status: "ready" },
  { id: "gen-004", name: "Executive Summary - Jan 2026", type: "executive", generatedAt: "2026-01-20T10:00:00Z", size: "2.1 MB", status: "ready" },
]
