import type {
  Scan,
  Vulnerability,
  ComplianceFramework,
  Threat,
  DashboardStats,
  TrendPoint,
  ReportTemplate,
  GeneratedReport,
} from "./types"

// --- Dashboard Stats ---
export const dashboardStats: DashboardStats = {
  totalScans: 247,
  activeScans: 3,
  criticalVulns: 12,
  complianceScore: 87,
  threatsDetected: 8,
  assetsMonitored: 1284,
  totalScansChange: 12,
  activeScanChange: -1,
  criticalVulnsChange: -3,
  complianceChange: 4,
  threatsChange: 2,
  assetsChange: 56,
}

// --- Scans ---
export const scans: Scan[] = [
  {
    id: "scan-001",
    name: "AWS Production Full Audit",
    target: "aws://prod-account-12345",
    cloudProvider: "AWS",
    status: "completed",
    scanType: "Full Audit",
    startTime: "2026-02-20T08:00:00Z",
    endTime: "2026-02-20T09:34:00Z",
    findingsCount: 47,
    progress: 100,
    criticalCount: 3,
    highCount: 8,
  },
  {
    id: "scan-002",
    name: "Azure AD Security Review",
    target: "azure://tenant-corp-001",
    cloudProvider: "Azure",
    status: "completed",
    scanType: "IAM Review",
    startTime: "2026-02-19T14:00:00Z",
    endTime: "2026-02-19T15:12:00Z",
    findingsCount: 23,
    progress: 100,
    criticalCount: 1,
    highCount: 5,
  },
  {
    id: "scan-003",
    name: "GCP Network Pentest",
    target: "gcp://project-analytics-prod",
    cloudProvider: "GCP",
    status: "running",
    scanType: "Network Pentest",
    startTime: "2026-02-21T06:00:00Z",
    endTime: null,
    findingsCount: 14,
    progress: 67,
    criticalCount: 2,
    highCount: 3,
  },
  {
    id: "scan-004",
    name: "AWS S3 Bucket Exposure Scan",
    target: "aws://prod-account-12345/s3",
    cloudProvider: "AWS",
    status: "running",
    scanType: "Storage Audit",
    startTime: "2026-02-21T07:30:00Z",
    endTime: null,
    findingsCount: 6,
    progress: 42,
    criticalCount: 1,
    highCount: 2,
  },
  {
    id: "scan-005",
    name: "Azure Container Security",
    target: "azure://aks-cluster-east",
    cloudProvider: "Azure",
    status: "pending",
    scanType: "Container Audit",
    startTime: "2026-02-21T10:00:00Z",
    endTime: null,
    findingsCount: 0,
    progress: 0,
    criticalCount: 0,
    highCount: 0,
  },
  {
    id: "scan-006",
    name: "GCP IAM Privilege Escalation",
    target: "gcp://project-analytics-prod/iam",
    cloudProvider: "GCP",
    status: "completed",
    scanType: "IAM Review",
    startTime: "2026-02-18T11:00:00Z",
    endTime: "2026-02-18T12:45:00Z",
    findingsCount: 31,
    progress: 100,
    criticalCount: 4,
    highCount: 7,
  },
  {
    id: "scan-007",
    name: "AWS Lambda Function Audit",
    target: "aws://prod-account-12345/lambda",
    cloudProvider: "AWS",
    status: "failed",
    scanType: "Serverless Audit",
    startTime: "2026-02-17T09:00:00Z",
    endTime: "2026-02-17T09:15:00Z",
    findingsCount: 0,
    progress: 12,
    criticalCount: 0,
    highCount: 0,
  },
  {
    id: "scan-008",
    name: "Azure SQL Database Review",
    target: "azure://sql-prod-westus",
    cloudProvider: "Azure",
    status: "running",
    scanType: "Database Audit",
    startTime: "2026-02-21T05:00:00Z",
    endTime: null,
    findingsCount: 9,
    progress: 78,
    criticalCount: 0,
    highCount: 3,
  },
]

// --- Vulnerabilities ---
export const vulnerabilities: Vulnerability[] = [
  {
    id: "vuln-001",
    title: "S3 Bucket Public Access Enabled",
    severity: "critical",
    category: "Storage Misconfiguration",
    cvssScore: 9.8,
    affectedResource: "s3://prod-data-exports",
    cloudProvider: "AWS",
    status: "open",
    description:
      "Public access is enabled on a production S3 bucket containing sensitive customer data exports. This allows unauthenticated access to the bucket contents from the internet.",
    remediation:
      "Disable public access via S3 Block Public Access settings. Review and rotate any exposed credentials. Enable S3 access logging.",
    scanId: "scan-001",
    discoveredAt: "2026-02-20T08:23:00Z",
  },
  {
    id: "vuln-002",
    title: "Root Account MFA Not Enabled",
    severity: "critical",
    category: "IAM Misconfiguration",
    cvssScore: 9.6,
    affectedResource: "iam://root-account",
    cloudProvider: "AWS",
    status: "open",
    description:
      "The AWS root account does not have multi-factor authentication enabled, exposing the account to credential-based attacks.",
    remediation:
      "Enable hardware or virtual MFA on the root account immediately. Set up an IAM admin user for daily operations instead.",
    scanId: "scan-001",
    discoveredAt: "2026-02-20T08:15:00Z",
  },
  {
    id: "vuln-003",
    title: "Overprivileged Service Account",
    severity: "high",
    category: "IAM Misconfiguration",
    cvssScore: 8.2,
    affectedResource: "gcp://sa-analytics@project.iam",
    cloudProvider: "GCP",
    status: "open",
    description:
      "Service account has Owner-level permissions on the entire GCP project, violating the principle of least privilege.",
    remediation:
      "Replace Owner role with fine-grained roles specific to the workload. Audit all service account key usage.",
    scanId: "scan-006",
    discoveredAt: "2026-02-18T11:34:00Z",
  },
  {
    id: "vuln-004",
    title: "Unencrypted RDS Instance",
    severity: "high",
    category: "Data Protection",
    cvssScore: 7.9,
    affectedResource: "rds://prod-userdb-east",
    cloudProvider: "AWS",
    status: "in_progress",
    description:
      "Production RDS PostgreSQL instance does not have encryption at rest enabled. Data on disk is stored in plaintext.",
    remediation:
      "Create a new encrypted snapshot and restore the database from it. Enable encryption for all future instances.",
    scanId: "scan-001",
    discoveredAt: "2026-02-20T08:45:00Z",
  },
  {
    id: "vuln-005",
    title: "Azure AD Conditional Access Bypass",
    severity: "critical",
    category: "Authentication",
    cvssScore: 9.1,
    affectedResource: "azure://conditional-access-policy-01",
    cloudProvider: "Azure",
    status: "open",
    description:
      "Legacy authentication protocols are not blocked by conditional access policies, allowing bypass of MFA requirements.",
    remediation:
      "Create a conditional access policy to block legacy authentication. Monitor sign-in logs for legacy protocol usage.",
    scanId: "scan-002",
    discoveredAt: "2026-02-19T14:22:00Z",
  },
  {
    id: "vuln-006",
    title: "Security Group Allows 0.0.0.0/0 SSH",
    severity: "high",
    category: "Network Misconfiguration",
    cvssScore: 8.5,
    affectedResource: "sg://sg-0a1b2c3d4e5f",
    cloudProvider: "AWS",
    status: "open",
    description:
      "Security group allows inbound SSH (port 22) from any IP address. This exposes instances to brute-force attacks.",
    remediation:
      "Restrict SSH access to known IP ranges or use AWS Systems Manager Session Manager for remote access.",
    scanId: "scan-001",
    discoveredAt: "2026-02-20T09:01:00Z",
  },
  {
    id: "vuln-007",
    title: "CloudTrail Logging Disabled",
    severity: "high",
    category: "Logging & Monitoring",
    cvssScore: 7.5,
    affectedResource: "cloudtrail://us-west-2",
    cloudProvider: "AWS",
    status: "remediated",
    description:
      "AWS CloudTrail is disabled in us-west-2 region, preventing audit trail of API calls.",
    remediation:
      "Enable multi-region CloudTrail with S3 log delivery and CloudWatch integration.",
    scanId: "scan-001",
    discoveredAt: "2026-02-20T08:30:00Z",
  },
  {
    id: "vuln-008",
    title: "GCP Firewall Rule Too Permissive",
    severity: "medium",
    category: "Network Misconfiguration",
    cvssScore: 6.5,
    affectedResource: "gcp://fw-allow-all-ingress",
    cloudProvider: "GCP",
    status: "open",
    description:
      "Firewall rule allows all ingress traffic on all ports from all sources. This effectively disables the network perimeter.",
    remediation:
      "Delete or restrict the firewall rule. Implement allow-list policies for specific ports and source ranges.",
    scanId: "scan-003",
    discoveredAt: "2026-02-21T06:15:00Z",
  },
  {
    id: "vuln-009",
    title: "Expired SSL Certificate",
    severity: "medium",
    category: "Data Protection",
    cvssScore: 5.9,
    affectedResource: "acm://api.example.com",
    cloudProvider: "AWS",
    status: "remediated",
    description:
      "SSL/TLS certificate for api.example.com expired 3 days ago, causing browser warnings and potential MITM exposure.",
    remediation:
      "Renew the certificate via ACM or upload a new certificate. Enable auto-renewal for ACM-managed certificates.",
    scanId: "scan-001",
    discoveredAt: "2026-02-20T09:10:00Z",
  },
  {
    id: "vuln-010",
    title: "Azure Storage Account Public Blob Access",
    severity: "high",
    category: "Storage Misconfiguration",
    cvssScore: 8.0,
    affectedResource: "azure://storageaccount01/blobs",
    cloudProvider: "Azure",
    status: "open",
    description:
      "Azure Storage Account allows public blob access, potentially exposing sensitive documents.",
    remediation:
      "Disable public blob access on the storage account. Review all containers for anonymous access level settings.",
    scanId: "scan-002",
    discoveredAt: "2026-02-19T14:50:00Z",
  },
  {
    id: "vuln-011",
    title: "IAM User Access Keys Not Rotated",
    severity: "medium",
    category: "IAM Misconfiguration",
    cvssScore: 6.2,
    affectedResource: "iam://user-deployer-ci",
    cloudProvider: "AWS",
    status: "accepted",
    description:
      "IAM user access keys have not been rotated in over 180 days, increasing risk of compromise.",
    remediation:
      "Rotate access keys immediately. Implement an automated key rotation policy with a 90-day maximum age.",
    scanId: "scan-001",
    discoveredAt: "2026-02-20T08:40:00Z",
  },
  {
    id: "vuln-012",
    title: "GCP Cloud SQL No Private IP",
    severity: "medium",
    category: "Network Misconfiguration",
    cvssScore: 6.0,
    affectedResource: "gcp://sql-analytics-prod",
    cloudProvider: "GCP",
    status: "in_progress",
    description:
      "Cloud SQL instance is configured with a public IP address, making it accessible from the internet.",
    remediation:
      "Configure the instance to use private IP only. Use Cloud SQL Proxy for secure connections.",
    scanId: "scan-006",
    discoveredAt: "2026-02-18T12:10:00Z",
  },
  {
    id: "vuln-013",
    title: "Missing VPC Flow Logs",
    severity: "low",
    category: "Logging & Monitoring",
    cvssScore: 4.0,
    affectedResource: "vpc://vpc-prod-east",
    cloudProvider: "AWS",
    status: "open",
    description:
      "VPC Flow Logs are not enabled for the production VPC, limiting network traffic visibility.",
    remediation:
      "Enable VPC Flow Logs with delivery to CloudWatch Logs or S3 for network traffic analysis.",
    scanId: "scan-001",
    discoveredAt: "2026-02-20T09:20:00Z",
  },
  {
    id: "vuln-014",
    title: "Azure Key Vault Soft Delete Disabled",
    severity: "low",
    category: "Data Protection",
    cvssScore: 3.8,
    affectedResource: "azure://keyvault-prod-01",
    cloudProvider: "Azure",
    status: "open",
    description:
      "Key Vault soft delete and purge protection are disabled, risking permanent key loss on accidental deletion.",
    remediation:
      "Enable soft delete and purge protection on the Key Vault. This cannot be reversed once enabled.",
    scanId: "scan-002",
    discoveredAt: "2026-02-19T15:00:00Z",
  },
  {
    id: "vuln-015",
    title: "GKE Node Auto-upgrade Disabled",
    severity: "info",
    category: "Configuration",
    cvssScore: 2.5,
    affectedResource: "gcp://gke-prod-cluster/node-pool-1",
    cloudProvider: "GCP",
    status: "accepted",
    description:
      "GKE node pool auto-upgrade is disabled, which may lead to running outdated and vulnerable node images.",
    remediation:
      "Enable auto-upgrade for the node pool or implement a regular manual upgrade schedule.",
    scanId: "scan-003",
    discoveredAt: "2026-02-21T06:30:00Z",
  },
  {
    id: "vuln-016",
    title: "Lambda Function Publicly Accessible",
    severity: "critical",
    category: "Serverless Misconfiguration",
    cvssScore: 9.3,
    affectedResource: "lambda://process-payments",
    cloudProvider: "AWS",
    status: "open",
    description:
      "Lambda function URL is publicly accessible without authentication, allowing unauthorized invocations of payment processing code.",
    remediation:
      "Add IAM authentication to the Lambda function URL or restrict access via API Gateway with authorization.",
    scanId: "scan-001",
    discoveredAt: "2026-02-20T08:55:00Z",
  },
]

// --- Compliance ---
export const complianceFrameworks: ComplianceFramework[] = [
  {
    name: "CIS Benchmarks v3.0",
    shortName: "CIS",
    score: 82,
    totalControls: 120,
    passedControls: 98,
    failedControls: 17,
    naControls: 5,
    controls: [
      { id: "cis-001", controlId: "1.1", description: "Avoid use of root account", status: "pass", category: "IAM", severity: "critical", framework: "CIS" },
      { id: "cis-002", controlId: "1.2", description: "Ensure MFA is enabled for all IAM users", status: "fail", category: "IAM", severity: "critical", framework: "CIS" },
      { id: "cis-003", controlId: "1.3", description: "Ensure credentials unused for 90 days are disabled", status: "pass", category: "IAM", severity: "high", framework: "CIS" },
      { id: "cis-004", controlId: "1.4", description: "Ensure access keys are rotated every 90 days", status: "fail", category: "IAM", severity: "high", framework: "CIS" },
      { id: "cis-005", controlId: "2.1", description: "Ensure CloudTrail is enabled in all regions", status: "pass", category: "Logging", severity: "high", framework: "CIS" },
      { id: "cis-006", controlId: "2.2", description: "Ensure CloudTrail log file validation is enabled", status: "pass", category: "Logging", severity: "medium", framework: "CIS" },
      { id: "cis-007", controlId: "3.1", description: "Ensure VPC flow logging is enabled in all VPCs", status: "fail", category: "Networking", severity: "medium", framework: "CIS" },
      { id: "cis-008", controlId: "3.2", description: "Ensure no security groups allow unrestricted SSH", status: "fail", category: "Networking", severity: "high", framework: "CIS" },
      { id: "cis-009", controlId: "4.1", description: "Ensure S3 bucket encryption is enabled", status: "pass", category: "Storage", severity: "high", framework: "CIS" },
      { id: "cis-010", controlId: "4.2", description: "Ensure S3 bucket public access is blocked", status: "fail", category: "Storage", severity: "critical", framework: "CIS" },
    ],
  },
  {
    name: "ISO 27001:2022",
    shortName: "ISO",
    score: 91,
    totalControls: 93,
    passedControls: 85,
    failedControls: 6,
    naControls: 2,
    controls: [
      { id: "iso-001", controlId: "A.5.1", description: "Information security policies", status: "pass", category: "Organizational", severity: "high", framework: "ISO" },
      { id: "iso-002", controlId: "A.6.1", description: "Screening of personnel", status: "pass", category: "People", severity: "medium", framework: "ISO" },
      { id: "iso-003", controlId: "A.7.1", description: "Physical security perimeters", status: "na", category: "Physical", severity: "medium", framework: "ISO" },
      { id: "iso-004", controlId: "A.8.1", description: "User endpoint devices", status: "pass", category: "Technology", severity: "high", framework: "ISO" },
      { id: "iso-005", controlId: "A.8.5", description: "Secure authentication", status: "fail", category: "Technology", severity: "critical", framework: "ISO" },
      { id: "iso-006", controlId: "A.8.9", description: "Configuration management", status: "pass", category: "Technology", severity: "high", framework: "ISO" },
      { id: "iso-007", controlId: "A.8.15", description: "Logging and monitoring", status: "pass", category: "Technology", severity: "high", framework: "ISO" },
      { id: "iso-008", controlId: "A.8.24", description: "Use of cryptography", status: "fail", category: "Technology", severity: "high", framework: "ISO" },
    ],
  },
  {
    name: "NIST CSF v2.0",
    shortName: "NIST",
    score: 78,
    totalControls: 108,
    passedControls: 84,
    failedControls: 19,
    naControls: 5,
    controls: [
      { id: "nist-001", controlId: "ID.AM-1", description: "Physical devices and systems are inventoried", status: "pass", category: "Identify", severity: "medium", framework: "NIST" },
      { id: "nist-002", controlId: "ID.AM-2", description: "Software platforms and applications are inventoried", status: "pass", category: "Identify", severity: "medium", framework: "NIST" },
      { id: "nist-003", controlId: "PR.AC-1", description: "Identities and credentials are managed", status: "fail", category: "Protect", severity: "critical", framework: "NIST" },
      { id: "nist-004", controlId: "PR.AC-3", description: "Remote access is managed", status: "fail", category: "Protect", severity: "high", framework: "NIST" },
      { id: "nist-005", controlId: "PR.DS-1", description: "Data-at-rest is protected", status: "fail", category: "Protect", severity: "high", framework: "NIST" },
      { id: "nist-006", controlId: "DE.AE-1", description: "Network operations baseline is established", status: "pass", category: "Detect", severity: "medium", framework: "NIST" },
      { id: "nist-007", controlId: "DE.CM-1", description: "Network is monitored for security events", status: "pass", category: "Detect", severity: "high", framework: "NIST" },
      { id: "nist-008", controlId: "RS.RP-1", description: "Response plan is executed during incidents", status: "pass", category: "Respond", severity: "high", framework: "NIST" },
    ],
  },
]

// --- Threats ---
export const threats: Threat[] = [
  {
    id: "thr-001",
    type: "Unauthorized Access Attempt",
    severity: "critical",
    source: "203.0.113.42",
    description: "Multiple failed SSH login attempts detected from suspicious IP across 5 EC2 instances in us-east-1.",
    timestamp: "2026-02-21T07:45:00Z",
    status: "active",
    relatedFindings: 3,
    recommendedAction: "Block IP at security group and WAF level. Review SSH key management policies.",
  },
  {
    id: "thr-002",
    type: "Privilege Escalation",
    severity: "critical",
    source: "Internal - sa-analytics@gcp",
    description: "Service account attempted to assign itself Owner role, indicating potential compromised credentials.",
    timestamp: "2026-02-21T06:20:00Z",
    status: "investigating",
    relatedFindings: 2,
    recommendedAction: "Rotate service account keys immediately. Review IAM audit logs for unauthorized changes.",
  },
  {
    id: "thr-003",
    type: "Data Exfiltration",
    severity: "high",
    source: "s3://prod-data-exports",
    description: "Unusual large data transfer detected from production S3 bucket to an external IP address.",
    timestamp: "2026-02-21T03:15:00Z",
    status: "active",
    relatedFindings: 4,
    recommendedAction: "Block the external IP. Review bucket access logs. Enable S3 Object Lock for critical data.",
  },
  {
    id: "thr-004",
    type: "Cryptomining Activity",
    severity: "high",
    source: "ec2://i-0abc123def456",
    description: "EC2 instance showing unusual CPU usage patterns consistent with cryptocurrency mining malware.",
    timestamp: "2026-02-20T22:30:00Z",
    status: "investigating",
    relatedFindings: 1,
    recommendedAction: "Isolate the instance. Create forensic image. Scan with GuardDuty for additional indicators.",
  },
  {
    id: "thr-005",
    type: "Suspicious API Calls",
    severity: "medium",
    source: "iam://admin-user-temp",
    description: "IAM user making unusual API calls to list all KMS keys and S3 buckets outside normal working hours.",
    timestamp: "2026-02-20T02:10:00Z",
    status: "resolved",
    relatedFindings: 2,
    recommendedAction: "Review CloudTrail logs for the user. Confirm activity was authorized.",
  },
  {
    id: "thr-006",
    type: "DDoS Attack",
    severity: "medium",
    source: "Multiple IPs",
    description: "Distributed denial of service attack detected targeting the application load balancer in us-west-2.",
    timestamp: "2026-02-20T18:00:00Z",
    status: "resolved",
    relatedFindings: 0,
    recommendedAction: "Verify AWS Shield Advanced is configured. Review WAF rate-based rules.",
  },
  {
    id: "thr-007",
    type: "Anomalous Login",
    severity: "medium",
    source: "azure://user-jdoe@corp",
    description: "User logged in from an unusual geographic location (Country: RU) with a new device fingerprint.",
    timestamp: "2026-02-21T01:45:00Z",
    status: "active",
    relatedFindings: 1,
    recommendedAction: "Force password reset. Review conditional access policies for geographic restrictions.",
  },
  {
    id: "thr-008",
    type: "Misconfiguration Exploit",
    severity: "low",
    source: "gcp://fw-allow-all-ingress",
    description: "Port scanning activity detected targeting instances exposed by overly permissive firewall rule.",
    timestamp: "2026-02-20T15:30:00Z",
    status: "resolved",
    relatedFindings: 1,
    recommendedAction: "Restrict firewall rules immediately. Implement network segmentation.",
  },
]

// --- Vulnerability Trend ---
export const vulnerabilityTrend: TrendPoint[] = (() => {
  const points: TrendPoint[] = []
  const now = new Date("2026-02-21")
  for (let i = 29; i >= 0; i--) {
    const d = new Date(now)
    d.setDate(d.getDate() - i)
    points.push({
      date: d.toISOString().slice(0, 10),
      critical: Math.max(5, Math.floor(15 - i * 0.2 + Math.sin(i) * 3)),
      high: Math.max(8, Math.floor(22 - i * 0.15 + Math.cos(i) * 4)),
      medium: Math.max(10, Math.floor(30 - i * 0.1 + Math.sin(i + 1) * 5)),
      low: Math.max(5, Math.floor(18 - i * 0.05 + Math.cos(i + 2) * 3)),
    })
  }
  return points
})()

// --- Report Templates ---
export const reportTemplates: ReportTemplate[] = [
  {
    id: "rpt-exec",
    name: "Executive Summary",
    description: "High-level security posture overview with risk scores, key findings, and strategic recommendations for leadership.",
    type: "executive",
    lastGenerated: "2026-02-19T10:00:00Z",
  },
  {
    id: "rpt-tech",
    name: "Technical Breakdown",
    description: "Detailed technical analysis of all discovered vulnerabilities with CVSS scores, attack vectors, and remediation steps.",
    type: "technical",
    lastGenerated: "2026-02-18T14:30:00Z",
  },
  {
    id: "rpt-comp",
    name: "Compliance Report",
    description: "Comprehensive compliance assessment against CIS, ISO 27001, and NIST frameworks with control-by-control analysis.",
    type: "compliance",
    lastGenerated: "2026-02-15T09:00:00Z",
  },
  {
    id: "rpt-full",
    name: "Full Audit Report",
    description: "Complete penetration testing report including methodology, scope, all findings, evidence, and remediation roadmap.",
    type: "full",
    lastGenerated: null,
  },
]

// --- Generated Reports ---
export const generatedReports: GeneratedReport[] = [
  { id: "gen-001", name: "Executive Summary - Feb 2026", type: "executive", generatedAt: "2026-02-19T10:00:00Z", size: "2.4 MB", status: "ready" },
  { id: "gen-002", name: "Technical Breakdown - Feb 2026", type: "technical", generatedAt: "2026-02-18T14:30:00Z", size: "8.1 MB", status: "ready" },
  { id: "gen-003", name: "CIS Compliance - Q1 2026", type: "compliance", generatedAt: "2026-02-15T09:00:00Z", size: "5.6 MB", status: "ready" },
  { id: "gen-004", name: "Executive Summary - Jan 2026", type: "executive", generatedAt: "2026-01-20T10:00:00Z", size: "2.1 MB", status: "ready" },
]
